server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/academy
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
