spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:mem:dcuser
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  mysql:
    console:
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 13MB

cloud:
  aws:
    s3:
      bucket: dcuser-bucket
    region: ap-northeast-2  # AWS ?? ??? ??
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

custom:
  jwt:
    expiration-period: 3600000
    secret-key: 12345678910abcdefghijklmnopqrstuvwxyz12345678910abcdefghijklmnopqrstuvwxyz